[platformio]
lib_dir = libraries

[env]
; https://github.com/pioarduino/platform-espressif32/releases
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
;- Arduino-esp32: 3.3.5
framework = arduino
lib_deps = 
	git+https://github.com/Bodmer/TFT_eSPI.git#V2.5.43  ;2.5.43
	git+https://github.com/adafruit/Adafruit_BusIO.git#1.14.1  ; 1.17.4
	git+https://github.com/me-no-dev/ESPAsyncWebServer.git
	ArduinoJSON@5.13
	HomeAssistant Component
	ArduinoOTA
	knolleary/PubSubClient@^2.8
	;TelnetSpy
	;NetworkClientSecure

build_flags = 
	-I include
	-Wno-unused-but-set-variable
	-DUSE_PANIC_WRAPPER
	-Wl,-wrap=panic_print_char
	; -Wl,-wrap=esp_panic_handler
	; -Wl,-wrap=panic_abort

extra_scripts = 
	pre:imagegen.py
	post:version.py
	post:secrets.py
	pre:linkdata.py

[env:lupa-espresso]
; V1 uses the original ESP32-WROOM-32(U)
;platform = espressif32@6.3.0
board = esp32dev
build_flags = ${env.build_flags}
	-I include/v1
	-include include/v1/tft_setup.h
	-mfix-esp32-psram-cache-issue
build_unflags =
    -DBOARD_HAS_PSRAM

; Port 3232
;upload_protocol = espota
;upload_port = lupa

monitor_filters = esp32_exception_decoder
;monitor_speed = 921600
upload_speed = 115200
;upload_port = COM3

[env:lupa-espresso-v2]
; V2 uses the ESP32-S3-WROOM-1(U) and a different IO pin mapping
board = esp32-s3-devkitc-1
build_flags = ${env.build_flags}
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
	-I include/v2
	-include include/v2/tft_setup.h

; Boot with just the bare minimum to have functional OTA
[env:lupa-espresso-recovery]
platform = espressif32@6.3.0
board = esp32dev
build_flags = ${env:lupa-espresso.build_flags} -I include/v1 -DFAILSAFE_RECOVERY
; Reduce upload speed to work around signal integrity issues
upload_speed = 115200
upload_port = COM3