[platformio]
lib_dir = libraries

[env]
; https://github.com/pioarduino/platform-espressif32/releases
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
;- Arduino-esp32: 3.3.5
framework = arduino
lib_deps = 
	git+https://github.com/Bodmer/TFT_eSPI.git#V2.5.43  ;2.5.43
	git+https://github.com/adafruit/Adafruit_BusIO.git#1.14.1  ; 1.17.4
	;git+https://github.com/me-no-dev/ESPAsyncWebServer.git
	ArduinoJSON@5.13
	HomeAssistant Component
	ArduinoOTA
	knolleary/PubSubClient@^2.8
	mongoose
	;TelnetSpy
	;NetworkClientSecure

build_flags = 
	-I include
	-Wno-unused-but-set-variable
	-DUSE_PANIC_WRAPPER
	-DBinary_h  ; workaround DEPRECATED redefinition warning in cores\esp32\binary.h
	-Wl,-wrap=panic_print_char
	; -Wl,-wrap=esp_panic_handler
	; -Wl,-wrap=panic_abort
	-Wl,-wrap=malloc
	-Wl,-wrap=calloc
	-Wl,-wrap=realloc
	-Os

extra_scripts = 
	pre:imagegen.py
	post:version.py
	post:secrets.py
	pre:linkdata.py

[env:lupa-espresso-v1]
; V1 uses the original ESP32-WROOM-32(U)
board = lupa-v1
build_unflags = -DBOARD_HAS_PSRAM

; Port 3232
;upload_protocol = espota
;upload_port = lupa

monitor_filters = esp32_exception_decoder
;monitor_speed = 921600
upload_speed = 115200
;upload_port = COM3

[env:lupa-espresso-v2]
; V2 uses the ESP32-S3-WROOM-1(U) and a different IO pin mapping
board = lupa-v2
build_flags = ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_filters = esp32_exception_decoder

; Boot with just the bare minimum to have functional OTA 
; (V1 only, since V2 has USB recovery available)
[env:lupa-espresso-recovery]
platform = espressif32@6.3.0
board = lupa-v1
build_flags = ${env:build_flags} -DFAILSAFE_RECOVERY
; Reduce upload speed to work around signal integrity issues
upload_speed = 115200
upload_port = COM3